### ISSUE TITLE
May i

### ISSUE THREAD

**Issue by Jade-Shi** [TadaoYamaoka/PaintsPyTorch#1]
may i ask for the whole project?and also i want to know if you faced the all green out put when use the original project?

**Comment by TadaoYamaoka** [comment]
Although it is only in Japanese, please refer to the blog article below for the project explanation and execution results.

https://tadaoyamaoka.hatenablog.com/entry/2023/02/19/163254

https://tadaoyamaoka.hatenablog.com/entry/2023/02/22/215742

**Comment by Jade-Shi** [comment]
thanks. I will read the blog to test the project.

**Comment by Jade-Shi** [comment]
after i train the model ，how should i test the model？because i can not test it from the project you provide

**Comment by TadaoYamaoka** [comment]
I used Jupyter notebook to run the tests. I'm attaching that notebook here.
[work.zip](https://github.com/TadaoYamaoka/PaintsPyTorch/files/15323648/work.zip)

**Comment by Jade-Shi** [comment]
thanks

**Comment by Jade-Shi** [comment]
i test the 128*128 model i train，but i face the same problem in paintschainer. All my out put pic is green.
![QQ图片20240516125608](https://github.com/TadaoYamaoka/PaintsPyTorch/assets/72867371/999d076f-4709-49b9-9d8a-4e9f4acad35c)
![QQ图片20240516125617](https://github.com/TadaoYamaoka/PaintsPyTorch/assets/72867371/9519f400-3b87-4f5a-a6ff-59e0a21f0249)
![QQ图片20240516125621](https://github.com/TadaoYamaoka/PaintsPyTorch/assets/72867371/e64100ee-78c1-46c7-bb4d-d37b3da15cd6)
i try many times in opencv version(which i think is the cvrColor problem.
Can you provide the opencv version which you use, or maybe you know the way to slove it? Thanks,it will help me a lot,wait for your answer.

**Comment by Jade-Shi** [comment]
i solve the problem，because my training epoch is too small.
